### PR TITLE
test: Disable typechecking while running tests

### PR DESCRIPTION
**Pull request by kulla**

### CODE REVIEW

**Comment by elbotho** [comment]
why the switch from `ts` to `cjs`?

**Comment by kulla** [comment]
> would `mjs` also be possible here?

No, the `module.exports` is a CommonJS way of exporting things. `mjs` is a JavaScript file in the ESM format (with `import` and `export`)...

**Comment by elbotho** [comment]
>No, the module.exports is a CommonJS way of exporting things. mjs is a JavaScript file in the ESM format (with import and export)...

I know…
but it was a esm before (when it was ts) and I was wondering if you needed to move to `module.exports`

**Comment by kulla** [comment]
> I know…
> but it was a esm before (when it was ts) and I was wondering if you needed to move to `module.exports`

Ah, no I understand -> Unless jest uses `require()` to load the config it should work. We need to try it...

**Comment by kulla** [comment]
@elbotho Looks good :smile:

**Comment by elbotho** [comment]
Nice! Let's be vigilant that cjs is not creeping back in 😉

**Review by hejtful — APPROVED** [review]

**Pull request merged**
